import javax.swing.*;
import javax.swing.border.*;
import java.awt.*;
import java.awt.event.*;
import java.awt.image.BufferedImage;
import javax.imageio.ImageIO;
import java.io.File;
import java.util.HashMap;
import java.util.Map;

/**
 * CardGameUI — A Blackjack game with a Java Swing frontend and C++ backend.
 * 
 * The game logic (deck, shuffling, dealing, scoring) is entirely in C++
 * via the CardGame class generated by JavaNativeLink.
 */
public class CardGameUI extends JFrame {

    // Native game engine
    private CardGame game;

    // Card images cache
    private final Map<String, Image> cardImages = new HashMap<>();
    private Image cardBack;

    // UI Components
    private JPanel dealerPanel;
    private JPanel playerPanel;
    private JLabel dealerScoreLabel;
    private JLabel playerScoreLabel;
    private JLabel statusLabel;
    private JLabel statsLabel;
    private JButton hitButton;
    private JButton standButton;
    private JButton newGameButton;

    // Colors
    private static final Color TABLE_GREEN = new Color(30, 100, 50);
    private static final Color DARK_GREEN = new Color(20, 70, 35);
    private static final Color GOLD = new Color(218, 165, 32);
    private static final Color SOFT_WHITE = new Color(240, 240, 230);

    // Card display size
    private static final int CARD_WIDTH = 100;
    private static final int CARD_HEIGHT = 145;

    public CardGameUI() {
        super("♠ Blackjack — JavaNativeLink Demo ♠");
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setResizable(false);

        // Initialize native game engine
        game = new CardGame();

        // Load card images
        loadCardImages();

        // Build UI
        initUI();

        pack();
        setLocationRelativeTo(null);
    }

    private void loadCardImages() {
        String cardsDir = "cards";
        String[] ranks = {"A", "2", "3", "4", "5", "6", "7", "8", "9", "T", "J", "Q", "K"};
        String[] suits = {"S", "H", "D", "C"};

        for (String r : ranks) {
            for (String s : suits) {
                String id = r + s;
                String filename = cardsDir + File.separator + id + ".png";
                try {
                    File f = new File(filename);
                    if (f.exists()) {
                        BufferedImage img = ImageIO.read(f);
                        cardImages.put(id, img.getScaledInstance(CARD_WIDTH, CARD_HEIGHT, Image.SCALE_SMOOTH));
                    }
                } catch (Exception e) {
                    System.err.println("Warning: Could not load " + filename);
                }
            }
        }

        // Load card back
        try {
            File backFile = new File(cardsDir + File.separator + "back.png");
            if (backFile.exists()) {
                BufferedImage img = ImageIO.read(backFile);
                cardBack = img.getScaledInstance(CARD_WIDTH, CARD_HEIGHT, Image.SCALE_SMOOTH);
            }
        } catch (Exception e) {
            System.err.println("Warning: Could not load card back image");
        }

        // Create fallback card back if not loaded
        if (cardBack == null) {
            cardBack = createFallbackCardBack();
        }
    }

    private Image createFallbackCardBack() {
        BufferedImage img = new BufferedImage(CARD_WIDTH, CARD_HEIGHT, BufferedImage.TYPE_INT_ARGB);
        Graphics2D g = img.createGraphics();
        g.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g.setColor(new Color(0, 50, 120));
        g.fillRoundRect(0, 0, CARD_WIDTH, CARD_HEIGHT, 12, 12);
        g.setColor(GOLD);
        g.drawRoundRect(2, 2, CARD_WIDTH - 5, CARD_HEIGHT - 5, 10, 10);
        g.drawRoundRect(8, 8, CARD_WIDTH - 17, CARD_HEIGHT - 17, 8, 8);
        // Draw a diamond pattern
        g.setColor(new Color(218, 165, 32, 120));
        for (int y = 15; y < CARD_HEIGHT - 15; y += 12) {
            for (int x = 15; x < CARD_WIDTH - 15; x += 12) {
                g.fillOval(x, y, 4, 4);
            }
        }
        g.dispose();
        return img;
    }

    private Image createFallbackCard(String id) {
        BufferedImage img = new BufferedImage(CARD_WIDTH, CARD_HEIGHT, BufferedImage.TYPE_INT_ARGB);
        Graphics2D g = img.createGraphics();
        g.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g.setColor(Color.WHITE);
        g.fillRoundRect(0, 0, CARD_WIDTH, CARD_HEIGHT, 12, 12);
        g.setColor(Color.DARK_GRAY);
        g.drawRoundRect(0, 0, CARD_WIDTH - 1, CARD_HEIGHT - 1, 12, 12);

        char rank = id.charAt(0);
        char suit = id.charAt(1);
        String rankStr = rank == 'T' ? "10" : String.valueOf(rank);
        String suitSymbol;
        Color suitColor;
        switch (suit) {
            case 'S': suitSymbol = "♠"; suitColor = Color.BLACK; break;
            case 'H': suitSymbol = "♥"; suitColor = Color.RED; break;
            case 'D': suitSymbol = "♦"; suitColor = Color.RED; break;
            case 'C': suitSymbol = "♣"; suitColor = Color.BLACK; break;
            default:  suitSymbol = "?"; suitColor = Color.GRAY; break;
        }

        g.setColor(suitColor);
        g.setFont(new Font("SansSerif", Font.BOLD, 20));
        g.drawString(rankStr, 8, 25);
        g.setFont(new Font("SansSerif", Font.PLAIN, 16));
        g.drawString(suitSymbol, 10, 45);

        g.setFont(new Font("SansSerif", Font.PLAIN, 40));
        FontMetrics fm = g.getFontMetrics();
        int sw = fm.stringWidth(suitSymbol);
        g.drawString(suitSymbol, (CARD_WIDTH - sw) / 2, CARD_HEIGHT / 2 + 15);

        g.dispose();
        return img;
    }

    private void initUI() {
        JPanel mainPanel = new JPanel(new BorderLayout(0, 0));
        mainPanel.setBackground(TABLE_GREEN);
        mainPanel.setBorder(BorderFactory.createLineBorder(DARK_GREEN, 4));

        // Title bar
        JPanel titlePanel = new JPanel();
        titlePanel.setBackground(DARK_GREEN);
        titlePanel.setBorder(new EmptyBorder(8, 0, 8, 0));
        JLabel titleLabel = new JLabel("♠ ♥ BLACKJACK ♦ ♣");
        titleLabel.setFont(new Font("SansSerif", Font.BOLD, 28));
        titleLabel.setForeground(GOLD);
        titlePanel.add(titleLabel);
        mainPanel.add(titlePanel, BorderLayout.NORTH);

        // Game area
        JPanel gameArea = new JPanel(new GridBagLayout());
        gameArea.setBackground(TABLE_GREEN);
        gameArea.setBorder(new EmptyBorder(15, 30, 15, 30));
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.weightx = 1.0;
        gbc.insets = new Insets(5, 0, 5, 0);

        // Dealer section
        gbc.gridx = 0; gbc.gridy = 0;
        dealerScoreLabel = new JLabel("Dealer", SwingConstants.CENTER);
        dealerScoreLabel.setFont(new Font("SansSerif", Font.BOLD, 18));
        dealerScoreLabel.setForeground(SOFT_WHITE);
        gameArea.add(dealerScoreLabel, gbc);

        gbc.gridy = 1;
        dealerPanel = new JPanel(new FlowLayout(FlowLayout.CENTER, 8, 5));
        dealerPanel.setOpaque(false);
        dealerPanel.setPreferredSize(new Dimension(600, CARD_HEIGHT + 20));
        gameArea.add(dealerPanel, gbc);

        // Status
        gbc.gridy = 2;
        statusLabel = new JLabel("Press 'New Game' to start!", SwingConstants.CENTER);
        statusLabel.setFont(new Font("SansSerif", Font.BOLD | Font.ITALIC, 22));
        statusLabel.setForeground(GOLD);
        statusLabel.setBorder(new EmptyBorder(10, 0, 10, 0));
        gameArea.add(statusLabel, gbc);

        // Player section
        gbc.gridy = 3;
        playerScoreLabel = new JLabel("Player", SwingConstants.CENTER);
        playerScoreLabel.setFont(new Font("SansSerif", Font.BOLD, 18));
        playerScoreLabel.setForeground(SOFT_WHITE);
        gameArea.add(playerScoreLabel, gbc);

        gbc.gridy = 4;
        playerPanel = new JPanel(new FlowLayout(FlowLayout.CENTER, 8, 5));
        playerPanel.setOpaque(false);
        playerPanel.setPreferredSize(new Dimension(600, CARD_HEIGHT + 20));
        gameArea.add(playerPanel, gbc);

        mainPanel.add(gameArea, BorderLayout.CENTER);

        // Bottom panel with buttons and stats
        JPanel bottomPanel = new JPanel(new BorderLayout());
        bottomPanel.setBackground(DARK_GREEN);
        bottomPanel.setBorder(new EmptyBorder(10, 20, 10, 20));

        // Buttons
        JPanel buttonPanel = new JPanel(new FlowLayout(FlowLayout.CENTER, 15, 5));
        buttonPanel.setOpaque(false);

        hitButton = createStyledButton("HIT", new Color(46, 139, 87));
        standButton = createStyledButton("STAND", new Color(178, 34, 34));
        newGameButton = createStyledButton("NEW GAME", new Color(70, 70, 150));

        hitButton.setEnabled(false);
        standButton.setEnabled(false);

        hitButton.addActionListener(e -> onHit());
        standButton.addActionListener(e -> onStand());
        newGameButton.addActionListener(e -> onNewGame());

        buttonPanel.add(hitButton);
        buttonPanel.add(standButton);
        buttonPanel.add(newGameButton);
        bottomPanel.add(buttonPanel, BorderLayout.CENTER);

        // Stats
        statsLabel = new JLabel("Wins: 0 | Losses: 0 | Pushes: 0", SwingConstants.CENTER);
        statsLabel.setFont(new Font("SansSerif", Font.PLAIN, 14));
        statsLabel.setForeground(SOFT_WHITE);
        statsLabel.setBorder(new EmptyBorder(5, 0, 0, 0));
        bottomPanel.add(statsLabel, BorderLayout.SOUTH);

        mainPanel.add(bottomPanel, BorderLayout.SOUTH);

        setContentPane(mainPanel);
    }

    private JButton createStyledButton(String text, Color bg) {
        JButton btn = new JButton(text);
        btn.setFont(new Font("SansSerif", Font.BOLD, 16));
        btn.setForeground(Color.WHITE);
        btn.setBackground(bg);
        btn.setFocusPainted(false);
        btn.setBorder(BorderFactory.createCompoundBorder(
            BorderFactory.createLineBorder(bg.darker(), 2),
            new EmptyBorder(8, 25, 8, 25)
        ));
        btn.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

        // Hover effect
        btn.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                if (btn.isEnabled()) btn.setBackground(bg.brighter());
            }
            @Override
            public void mouseExited(MouseEvent e) {
                btn.setBackground(bg);
            }
        });
        return btn;
    }

    private void onNewGame() {
        game.startNewGame();
        hitButton.setEnabled(true);
        standButton.setEnabled(true);
        updateUI();
    }

    private void onHit() {
        game.playerHit();
        updateUI();
    }

    private void onStand() {
        game.playerStand();
        updateUI();
    }

    private void updateUI() {
        String status = game.getGameStatus();
        boolean gameOver = game.isGameOver() != 0;

        // Update dealer cards
        dealerPanel.removeAll();
        String dealerCardsStr = game.getDealerCards();
        if (!dealerCardsStr.isEmpty()) {
            String[] dealerCards = dealerCardsStr.split(",");
            for (int i = 0; i < dealerCards.length; i++) {
                Image img;
                if (!gameOver && i > 0) {
                    // Hide dealer's hole cards while playing
                    img = cardBack;
                } else {
                    img = getCardImage(dealerCards[i].trim());
                }
                dealerPanel.add(new JLabel(new ImageIcon(img)));
            }
        }

        // Update player cards
        playerPanel.removeAll();
        String playerCardsStr = game.getPlayerCards();
        if (!playerCardsStr.isEmpty()) {
            String[] playerCards = playerCardsStr.split(",");
            for (String card : playerCards) {
                Image img = getCardImage(card.trim());
                playerPanel.add(new JLabel(new ImageIcon(img)));
            }
        }

        // Update scores
        int playerScore = game.getPlayerScore();
        int dealerScore = game.getDealerScore();

        playerScoreLabel.setText("Player — Score: " + playerScore);
        if (gameOver) {
            dealerScoreLabel.setText("Dealer — Score: " + dealerScore);
        } else {
            // Show only the visible card's value
            dealerScoreLabel.setText("Dealer — Score: ?");
        }

        // Update status message
        switch (status) {
            case "playing":
                statusLabel.setText("Your turn — Hit or Stand?");
                statusLabel.setForeground(SOFT_WHITE);
                break;
            case "player_bust":
                statusLabel.setText("💥 BUST! You went over 21!");
                statusLabel.setForeground(new Color(255, 80, 80));
                hitButton.setEnabled(false);
                standButton.setEnabled(false);
                break;
            case "dealer_bust":
                statusLabel.setText("🎉 DEALER BUSTS! You win!");
                statusLabel.setForeground(GOLD);
                hitButton.setEnabled(false);
                standButton.setEnabled(false);
                break;
            case "player_win":
                statusLabel.setText("🏆 YOU WIN!");
                statusLabel.setForeground(GOLD);
                hitButton.setEnabled(false);
                standButton.setEnabled(false);
                break;
            case "dealer_win":
                statusLabel.setText("😞 Dealer wins.");
                statusLabel.setForeground(new Color(255, 120, 120));
                hitButton.setEnabled(false);
                standButton.setEnabled(false);
                break;
            case "push":
                statusLabel.setText("🤝 Push — it's a tie!");
                statusLabel.setForeground(SOFT_WHITE);
                hitButton.setEnabled(false);
                standButton.setEnabled(false);
                break;
        }

        // Update stats
        statsLabel.setText("Wins: " + game.getPlayerWins()
                + " | Losses: " + game.getDealerWins()
                + " | Pushes: " + game.getPushes());

        dealerPanel.revalidate();
        dealerPanel.repaint();
        playerPanel.revalidate();
        playerPanel.repaint();
    }

    private Image getCardImage(String cardId) {
        Image img = cardImages.get(cardId);
        if (img == null) {
            img = createFallbackCard(cardId);
            cardImages.put(cardId, img);
        }
        return img;
    }

    public static void main(String[] args) {
        // Set native look-and-feel
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception ignored) {}

        SwingUtilities.invokeLater(() -> {
            CardGameUI ui = new CardGameUI();
            ui.setVisible(true);
        });
    }
}
